# Generated by Django 4.1.7 on 2023-03-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Category",
            new_name="category",
        ),
    ]
